config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView

from tweets.views import (
    tweets_feed_view,
    tweets_detail_view, 
    tweets_list_view,
    )
from accounts.views import (
    login_view,
    logout_view,
    register_view,
)
urlpatterns = [
    path('admin/', admin.site.urls),

    path('', tweets_feed_view, name='tweet_feed'),
    path('<int:tweet_id>/', tweets_detail_view, name='tweet_detail'),
    path('global_tweets/', tweets_list_view, name='tweet_list'),

    path('login/',login_view, name='login'),
    path('logout/',logout_view, name='logout'),
    path('register/',register_view, name='register'),

    re_path(r'profiles?/', include("profiles.urls", namespace='profile')),

    path('api/tweets/', include("tweets.rest_api.urls")),
    re_path(r'api/profiles?/', include("profiles.rest_api.urls")),


]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

profiles/urls.py
from django.urls import path
from .views import profile_detail_view, profile_update_view

app_name='profile'

urlpatterns = [
    path('<str:username>/edit/',  profile_update_view, name='update'),
    path('<str:username>/detail/',  profile_detail_view, name='detail'),
]

templates/components/form.html
<form method="POST">
    
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary btn-sm" type='submit'>
        {% if btn_label %}
            {{btn_label}}
         {% else %}
         Create tweet
         {% endif %}
        </button>
            
</form>

templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-tweet mb-3">
    <a class="navbar-tweet navbar-brand " href="{% url 'tweet_feed' %}">
        Tweetme2
    </a>
    
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tweet_list' %}">All Tweets</a>
          </li>
          <li class="nav-item">
          
          {% if request.user.is_authenticated %}
        
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{request.user.username}}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" 
                href="{% url 'profile:update' username=request.user %}">Edit</a>
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </li>
        
        {% else %}
        
            <a class="nav-link" href="{% url 'login' %}">Log In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
          </li>
        {% endif %}
            
        
      </ul>
      <!-- <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> -->
    </div>
  </nav>